version: "3"

services:

  flask:
    build: .
    ports:
      - "80:5000"
    depends_on:
      - redis
    networks:
      - test_net

  redis:
    image: redis:3.2.0
    networks:
      - test_net

networks:
  test_net:
    driver: bridge